# Run this AFTER import_all.ps1

npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('size_tables', '[{""id"":""table_1775540374264_59s1u4rmb8g"",""name"":""Compression Top Size"",""unit"":""cm"",""columns"":[{""id"":""chest"",""name"":""Length"",""description"":""Measure from the highest point of the shoulder (near the collar) straight down to the bottom hem.""},{""id"":""waist"",""name"":""Width"",""description"":""Lay the top flat. Measure straight across from one armpit to the other.""}],""rows"":[{""id"":""m"",""label"":""M"",""values"":{""chest"":""63"",""waist"":""33""}},{""id"":""l"",""label"":""L"",""values"":{""chest"":""65"",""waist"":""35""}},{""id"":""xl"",""label"":""XL"",""values"":{""chest"":""68"",""waist"":""38""}}]}]')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('finance_data', '{""batches"":[{""id"":""id_1775498835645_jolc2"",""name"":""FLEX 01 (Half-sleeve & Sleeveless)"",""units"":102,""production_cost"":61200,""intl_shipping"":0,""customs"":0,""other"":0,""date"":""2026-04-06"",""notes"":""""}],""expenses"":[{""id"":""id_1775499075989_px1la"",""label"":""Facebook page boosting"",""category"":""Marketing / Ads"",""amount"":326.91,""date"":""2026-04-06"",""notes"":""""},{""id"":""id_1775886875087_8scog"",""label"":""AI subscription"",""category"":""Website / Tech"",""amount"":6698.25,""date"":""2026-04-11"",""notes"":""""}]}')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('hero_tagline_lineheight', '1.5')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('free_delivery', 'true')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('banner_bg', '#ffffff')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('delivery_rajshahi', '100')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('delivery_rangpur', '150')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('review_3_location', 'Sylhet')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('size_l_waist', '35')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('size_m_hips', '40-42')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('size_m_chest', '63')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('delivery_other', '150')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('about_story_body3', 'But Flextreme is more than gym wear. It represents a mindset.
**A mindset of discipline.**
**A mindset of relentless improvement.**
**A mindset that refuses to settle.**
When you wear Flextreme, you are not just wearing training apparel.
You are wearing a symbol of hard work, ambition, and the extreme pursuit of becoming stronger every day.
Work Hard. Flex Extreme.')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('banner_speed', '60')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('size_rows', '[{""id"":""m"",""label"":""M"",""values"":{""chest"":""63"",""waist"":""33""}},{""id"":""l"",""label"":""L"",""values"":{""chest"":""65"",""waist"":""35""}},{""id"":""xl"",""label"":""XL"",""values"":{""chest"":""66"",""waist"":""38""}}]')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('review_1_text', 'Finally gym wear that actually fits right. The compression tee is unreal — stays dry the whole session and looks clean.')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('about_values_title', 'Our Values')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('hero_badge_opacity', '0.5')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('delivery_bogra', '150')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('delivery_narayanganj', '150')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('hero_bg_video', 'https://rngqnqqvnnzscwevwbpj.supabase.co/storage/v1/object/public/products/hero-video-1776145106997.mp4')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('hero_tagline_opacity', '0.8')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('stats_products', '4')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('size_xs_hips', '34-36')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('about_story_body1', 'Every great brand starts with a belief.

**Flextreme** was created for people who refuse to stay average — people who push harder, train longer, and go beyond their limits.')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('review_3_name', 'Usman R.')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('business_hours', ' [{""day"":""Saturday – Thursday"",""hours"":""9:00 AM – 9:00 PM""},{""day"":""Friday"",""hours"":""3:00 PM – 9:00 PM""}]')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('about_story_title', 'The Flextreme Story')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('banner_text', ' “FLEX100 Membership — First 100 Only ⚡” Limited spots available  ✓ Cash on Delivery  ·  ✓ Pay when it arrives  ·  ✓ Zero advance payment')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('delivery_sylhet', '150')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('size_unit', 'cm')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('size_xl_hips', '46-48')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('delivery_groups', '[{""id"":""dhaka"",""name"":""Dhaka Division"",""zones"":[{""id"":""dhaka_city"",""name"":""Dhaka City"",""charge"":""150"",""days"":""2-3""},{""id"":""dhaka_district"",""name"":""Dhaka District"",""charge"":""150"",""days"":""2-3""},{""id"":""narayanganj"",""name"":""Narayanganj"",""charge"":""150"",""days"":""2-3""},{""id"":""gazipur"",""name"":""Gazipur"",""charge"":""150"",""days"":""2-3""},{""id"":""mymensingh"",""name"":""Mymensingh"",""charge"":""150"",""days"":""2-3""}]},{""id"":""chittagong"",""name"":""Chittagong Division"",""zones"":[{""id"":""chittagong"",""name"":""Chittagong"",""charge"":""150"",""days"":""2-3""},{""id"":""comilla"",""name"":""Comilla"",""charge"":""150"",""days"":""2-3""}]},{""id"":""others"",""name"":""Other Divisions or Cities"",""zones"":[{""id"":""sylhet"",""name"":""Sylhet"",""charge"":""150"",""days"":""2-3""},{""id"":""rajshahi"",""name"":""Rajshahi"",""charge"":""150"",""days"":""2-3""},{""id"":""khulna"",""name"":""Khulna"",""charge"":""70-100"",""days"":""1-2""},{""id"":""jessore"",""name"":""Jessore"",""charge"":""150"",""days"":""2-3""},{""id"":""bogra"",""name"":""Bogra"",""charge"":""150"",""days"":""2-3""},{""id"":""barisal"",""name"":""Barisal"",""charge"":""150"",""days"":""2-3""},{""id"":""rangpur"",""name"":""Rangpur"",""charge"":""150"",""days"":""2-3""},{""id"":""other"",""name"":""All Other Districts"",""charge"":""150"",""days"":""2-3""}]}]')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('hero_bg_position', 'center')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('review_2_text', 'Ordered the Pro Shorts and joggers together. Delivery was fast, quality is premium. Will definitely order again.')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('faqs', '[{""id"":""faq1"",""question"":""How do I place an order?"",""answer"":""Simply visit our Products page, choose your item, select size and color, fill in your details and click Order Now. We confirm via WhatsApp or direct call and deliver Cash on Delivery.""},{""id"":""faq2"",""question"":""What payment methods do you accept?"",""answer"":""We accept Cash on Delivery (COD) only. Pay when your order arrives at your door — no advance payment needed.""},{""id"":""faq3"",""question"":""How long does delivery take?"",""answer"":""KhulnaCity: 1-2 days. Other cities: 2-5 days depending on location.""},{""id"":""faq4"",""question"":""Can I return or exchange my order?"",""answer"":""Yes! If there is any issue with your order, contact us on WhatsApp within 48 hours of receiving it and we will arrange an exchange or refund.""}]')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('color_theme', '{""primary"":""#000000"",""accent"":""#ffffff"",""bg"":""#ffffff"",""text"":""#000000"",""btnBg"":""#000000"",""btnText"":""#ffffff""}')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('hero_headline_spacing', '-0.05')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('about_team_title', 'Behind Flextreme')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('cta_headline', 'START YOUR JOURNEY.')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('hero_show_watermark', 'true')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('whatsapp_number', '8801935962421')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('stats_rating', '5 Star')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('hero_bg_pos_y', '62.776446931691396')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('about_hero_headline', NULL)"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('about_values', '[{""number"":""01"",""title"":""Performance First"",""description"":""Every design decision starts with one question: Does this help athletes perform better?""},{""number"":""02"",""title"":""Athletes Designing for Athletes"",""description"":""We are athletes ourselves, creating performance gear built from real training experience.""},{""number"":""03"",""title"":""No-Compromise Quality"",""description"":""Premium fabrics, precision stitching, and rigorous testing to ensure durability and performance.""},{""number"":""04"",""title"":""Accessible Excellence"",""description"":""Elite performance gear without unnecessary markups.""}]')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('youtube_url', NULL)"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('product_categories', '[{""id"":""cat_tops"",""name"":""tops"",""subcategories"":[""compression top""]},{""id"":""cat_bottoms"",""name"":""bottoms"",""subcategories"":[]},{""id"":""cat_accessories"",""name"":""accessories"",""subcategories"":[]}]')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('review_3_rating', '5')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('hero_headline', 'LOOK|BIGGER|INSTANTLY')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('size_xxl_hips', '49-51')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('cta_subtext', 'Join our growing community of athletes who train in Flextreme. Cash on Delivery. Nationwide shipping across Bangladesh.')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('size_xs_waist', '26-28')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('hero_overlay_opacity', '0.5')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('hero_bg_image', 'https://res.cloudinary.com/dorki2ipl/image/upload/v1776876625/flextreme/hero/uxjhvjx96uk6j0qwmdob.jpg')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('review_1_rating', '5')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('delivery_dhaka_city', '150')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('hero_bg_type', 'image')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('delivery_mymensingh', '150')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('size_s_hips', '37-39')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('hero_bg_pos_x', '11.948429333623697')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('review_1_location', 'Dhaka')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('hero_tagline_maxwidth', '460')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('review_1_name', 'Ahmed K.')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('size_s_waist', '29-31')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('size_xl_chest', '66')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('hero_cta_primary', 'Buy Now')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('stats_customers', '7')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('banner_color', '#030303')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('brand_story', 'The name **Flextreme** comes from two powerful ideas: **Flex** and **Extreme**.
In fitness culture, flexing is more than showing muscles. It represents the result of discipline, sacrifice, and relentless effort. It is the moment when hard work becomes visible.
Extreme represents the mindset of pushing past comfort zones — going one more rep, one more set, one more mile when others stop.
By combining these two ideas, Flextreme was born.
Our slogan, “**Work Hard, Flex Extreme**,” reflects the philosophy behind the brand. Success is not given; it is earned through effort, dedication, and consistency.
The logo itself carries meaning. Designed with a triangular shape, it represents strength, balance, and growth. Within the triangle, the letters **F**, **L**, **E**, and **X** are embedded, forming the foundation of the brand.')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('delivery_comilla', '150')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('size_xxl_waist', '41-43')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('delivery_dhaka_district', '150')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('hero_tagline_size', '1.1')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('hero_watermark_opacity', '0.075')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('instagram_url', 'https://instagram.com/flextreme.fit')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('delivery_khulna', '70')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('about_team', '[{""name"":""The Founder"",""role"":""Athlete and Visionary"",""description"":""I worked hard to build my physique, but regular gym wear didn’t reflect the effort I put into training. When I discovered compression wear, it completely changed how my physique looked. That experience inspired me to create Flextreme.""},{""name"":""The Design Team"",""role"":""Performance Designers"",""description"":""Our design philosophy is simple: athletes designing for athletes, creating gym wear that enhances performance and showcases the physique.""},{""name"":""The Community"",""role"":""Our Growing Community"",""description"":""The Flextreme community is built for people who train hard, push their limits, and support each other to become stronger every day.""}]')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('store_phone', '+8801935962421')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('delivery_gazipur', '150')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('hero_bg_opacity', '0.8')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('store_email', 'flextremefit@gmail.com')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('banner_enabled', 'false')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('size_m_waist', '33')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('about_story', 'Flextreme was built by athletes, for athletes. We got tired of choosing between gear that looks good and gear that performs. So we built both.')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('review_2_rating', '5')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('size_xl_waist', '38')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('cursor_type', 'normal')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('hero_watermark_size', '120')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('size_xs_chest', '32-34')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('size_l_hips', '43-45')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('review_2_name', 'Bilal M.')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('hero_space_button', '2')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('hero_badge', 'Premium Gym Wear')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('hero_tagline', 'Only 100 will ever exist — claim yours before it’s gone.
🔥 Limited stock available
🚚 Cash on Delivery —No advance payment required')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('hero_cta_secondary', 'hidden')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('facebook_url', 'https://facebook.com/flextremefit')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('delivery_barisal', '150')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('hero_bg_scale', '1')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('size_columns', '[{""id"":""chest"",""name"":""Length""},{""id"":""waist"",""name"":""Width""}]')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('review_2_location', 'Chittagong')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('hero_padding_top', '80')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('hero_headline_weight', '790')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('stats_cod', '100%')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('delivery_jessore', '150')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('review_3_text', 'The muscle tank is everything. Fits perfectly, highlights the physique, and the fabric is super comfortable.')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('size_xxl_chest', '47-49')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('tiktok_url', NULL)"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('size_s_chest', '35-37')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('delivery_chittagong', '150')"
npx wrangler d1 execute flextreme-db --remote --command="INSERT OR REPLACE INTO settings (key, value) VALUES ('size_l_chest', '65')"
