name = "flextreme"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "flextreme-db"
database_id = "d77abb13-2f34-4b57-b8d4-6893338dce68"

[observability]
enabled = true
